collision_spheres:
  # Right Arm
  right_shoulder_pitch_link:
    - center: [-0.004, -0.05, -0.001]
      radius: 0.052
  right_shoulder_roll_link:
    - center: [0.012, -0.002, -0.069]
      radius: 0.04
  right_shoulder_yaw_link:
    - center: [0.0, 0.0, -0.02]
      radius: 0.04
    - center: [0.0, 0.0, -0.05]
      radius: 0.04
    - center: [0.0, 0.0, -0.08]
      radius: 0.04
  
  right_elbow_link:
    - center: [0.02, 0.0, 0.0]
      radius: 0.035
    - center: [0.05, 0.0, 0.0]
      radius: 0.035
    - center: [0.08, 0.0, 0.0]
      radius: 0.035
      
  right_wrist_roll_link:
    - center: [0.02, 0.0, 0.0]
      radius: 0.03
      
  right_wrist_pitch_link:
    - center: [0.02, 0.0, 0.0]
      radius: 0.03
      
  right_wrist_yaw_link:
    - center: [0.02, 0.0, 0.0]
      radius: 0.03
      
  right_rubber_hand:
    - center: [0.02, 0.0, 0.0]
      radius: 0.03
    - center: [0.05, 0.0, 0.0]
      radius: 0.025
    - center: [0.05, -0.02, 0.0] # approximate finger (flipped Y)
      radius: 0.02
    - center: [0.05, 0.02, 0.0] # approximate finger (flipped Y)
      radius: 0.02
