# Corresponds to the left arm of the G1 robot with 23 dofs 
# https://github.com/unitreerobotics/unitree_ros/tree/master/robots/g1_description
# 
robot_cfg:
  kinematics:
    base_link: pelvis
    ee_link: dummy_ee_left_link # left_wrist_roll_rubber_hand # "left_hand_ee"
    use_usd_kinematics: False

    # File paths
    urdf_path: "robot/g1_23dof_description/g1_23dofs_cfgs/g1_23dof.urdf"
    # asset_root_path: "robot/g1_humanoid"
    # usd_path: "robot/g1_humanoid/g1.usd"
    # usd_robot_root: "/g1"

    # Collision configuration
    collision_link_names:  # Name of links to compute sphere positions for use in collision checking.
      # body
      - pelvis
      - torso_link
      - head_link
      # left hip 
      - left_hip_pitch_link
      - left_hip_roll_link
      - left_hip_yaw_link
      
      # right hip
      - right_hip_pitch_link
      - right_hip_roll_link
      - right_hip_yaw_link
      

      # left arm - 5 links
      - left_shoulder_pitch_link
      - left_shoulder_roll_link
      - left_shoulder_yaw_link
      - left_elbow_link
      - left_wrist_roll_rubber_hand
      # right arm - 5 links
      - right_shoulder_pitch_link
      - right_shoulder_roll_link
      - right_shoulder_yaw_link
      - right_elbow_link
      - right_wrist_roll_rubber_hand
      
      # - world
      # - pelvis_contour_link
      # - left_hip_roll_link
      # - left_hip_roll_link
      # - left_knee_link
      # - left_ankle_pitch_link
      # - left_ankle_roll_link
      # - right_hip_roll_link
      # - right_hip_yaw_link
      # - right_knee_link
      # - right_ankle_pitch_link
      # - right_ankle_roll_link      
      # - waist_yaw_fixed_link
      # - logo_link
      # - waist_support_link
      # - imu_in_torso
      # - imu_in_pelvis

    mesh_link_names: # Names of links to load meshes for visualization. This is only used for exporting visualizations.
      - world
      - pelvis
      - pelvis_contour_link
      - left_hip_yaw_link
      - left_hip_roll_link
      - left_hip_pitch_link
      - left_knee_link
      - left_ankle_pitch_link
      - left_ankle_roll_link
      - right_hip_pitch_link
      - right_hip_roll_link
      - right_hip_yaw_link
      - right_knee_link
      - right_ankle_pitch_link
      - right_ankle_roll_link
      - waist_yaw_fixed_link
      - torso_link
      - logo_link
      - head_link
      - waist_support_link
      - imu_in_torso
      - imu_in_pelvis

      # left arm - 5 links
      - left_shoulder_pitch_link
      - left_shoulder_roll_link
      - left_shoulder_yaw_link
      - left_elbow_link
      - left_wrist_roll_rubber_hand
      - dummy_ee_left_link

      # right arm - 5 links
      - right_shoulder_pitch_link
      - right_shoulder_roll_link
      - right_shoulder_yaw_link
      - right_elbow_link
      - right_wrist_roll_rubber_hand
      
    # Freeze lower-body and torso joints so that only the arms/hands are actuated
    lock_joints: # Lock active joints in the kinematic tree. This will convert the joint to a fixed joint with joint angle given from this dictionary.
      left_hip_pitch_joint: 0.0 # standing position
      left_hip_roll_joint: 0.0
      left_hip_yaw_joint: 0.0
      
      right_hip_pitch_joint: 0.0
      right_hip_roll_joint: 0.0
      right_hip_yaw_joint: 0.0

      waist_yaw_joint: 0.0
      # right arm joints
      right_shoulder_pitch_joint: 0.5 # to the side
      right_shoulder_roll_joint: -0.5
      right_shoulder_yaw_joint: 0.0
      right_elbow_joint: 1.2
      right_wrist_roll_joint: 0.0
      
      # floating_base_joint: -0.4
      # pelvis_contour_joint: -0.4
      # left_hip_roll_joint: 0.05
      # left_hip_yaw_joint: -0.05
      # left_knee_joint: 0.0
      # left_ankle_pitch_joint: 0.0
      # left_ankle_roll_joint: 0.8
      
      # right_hip_roll_joint: -0.3
      # right_hip_yaw_joint: -0.3
      # right_knee_joint: 0.0
      # right_ankle_pitch_joint: 0.0
      # right_ankle_roll_joint: -1.4
      # waist_yaw_fixed_joint: 0.0
      # logo_joint: 1.2
      # head_joint: 0.0
      # waist_support_joint: -0.8
      # imu_in_torso_joint: -0.8
      # imu_in_pelvis_joint: -0.3
      # d435_joint: -0.8
      # mid360_joint: -0.3
      
      # left arm joints (unlocked)
      # left_shoulder_pitch_joint: -1.4
      # left_shoulder_roll_joint: 0.2
      # left_shoulder_yaw_joint: 0.0
      # left_elbow_joint: 1.2
      # left_wrist_roll_joint: 0.0
      
      
    
    collision_sphere_buffer: 0.0001

    self_collision_buffer: # making collision spheres bigger to avoid self-collisions
      
      # body
      pelvis: 0.0001
      torso_link: 0.0001
      head_link: 0.0001
      
      # left arm
      left_shoulder_pitch_link: 0.0001
      left_shoulder_roll_link: 0.0001
      left_shoulder_yaw_link: 0.0001
      left_elbow_link: 0.0001
      left_wrist_roll_rubber_hand: 0.0001

      # left hip
      left_hip_pitch_link: 0.0001
      left_hip_roll_link: 0.0001
      left_hip_yaw_link: 0.0001

      

      # right arm    
      right_hip_pitch_link: 0.0001
      right_shoulder_roll_link: 0.0001
      right_elbow_link: 0.0001
      right_shoulder_pitch_link: 0.0001
      right_shoulder_yaw_link: 0.0001
      right_wrist_roll_rubber_hand: 0.0001
      
      # right hip
      right_hip_pitch_link: 0.0001
      right_hip_roll_link: 0.0001
      right_hip_yaw_link: 0.0001

    self_collision_ignore: {
      "left_shoulder_pitch_link":["head_link","left_shoulder_roll_link", "left_shoulder_yaw_link", "left_elbow_link", "torso_link"],
      "left_shoulder_roll_link":["head_link","left_shoulder_pitch_link", "left_shoulder_yaw_link", "left_elbow_link", "torso_link"],
      "left_shoulder_yaw_link": ["left_shoulder_roll_link", "left_shoulder_pitch_link", "left_elbow_link"],
      "left_elbow_link": ["left_shoulder_roll_link", "left_shoulder_pitch_link", "left_shoulder_yaw_link","left_wrist_roll_rubber_hand"],
      "left_wrist_roll_rubber_hand": ["left_elbow_link"],

      "right_shoulder_pitch_link": ["head_link","right_shoulder_roll_link", "right_shoulder_yaw_link", "right_elbow_link", "torso_link"],
      "right_shoulder_roll_link": ["head_link","right_shoulder_pitch_link", "right_shoulder_yaw_link", "right_elbow_link", "torso_link"],
      "right_shoulder_yaw_link": ["right_shoulder_pitch_link", "right_shoulder_roll_link", "right_elbow_link"],
      "right_elbow_link": ["right_shoulder_pitch_link", "right_shoulder_roll_link", "right_shoulder_yaw_link", "right_wrist_roll_rubber_hand"],
      "right_wrist_roll_rubber_hand": ["right_elbow_link"],

      "pelvis": ["torso_link", "left_hip_pitch_link", "right_hip_pitch_link"],      
      "torso_link": ["head_link","pelvis","left_shoulder_pitch_link","right_shoulder_pitch_link","left_shoulder_roll_link","right_shoulder_roll_link"],
      "head_link": ["torso_link","left_shoulder_pitch_link","right_shoulder_pitch_link","left_shoulder_roll_link","right_shoulder_roll_link"],
      "left_hip_pitch_link": ["left_hip_roll_link", "left_hip_yaw_link","left_shoulder_pitch_link", "left_shoulder_roll_link", "torso_link"],
      "left_hip_roll_link": ["left_hip_pitch_link", "left_hip_yaw_link","left_shoulder_pitch_link", "left_shoulder_roll_link", "left_shoulder_yaw_link" ],
      "left_hip_yaw_link": ["left_hip_pitch_link", "left_hip_roll_link", "left_shoulder_pitch_link", "left_shoulder_roll_link", "left_shoulder_yaw_link"],
      "right_hip_pitch_link": ["right_hip_roll_link", "right_hip_yaw_link","right_shoulder_pitch_link", "right_shoulder_roll_link", "torso_link"],
      "right_hip_roll_link": ["right_hip_pitch_link", "right_hip_yaw_link","right_shoulder_pitch_link", "right_shoulder_roll_link", "torso_link"],
      "right_hip_yaw_link": ["right_hip_pitch_link", "right_hip_roll_link", "right_shoulder_pitch_link", "right_shoulder_roll_link", "torso_link"],
      }

    collision_spheres: spheres/g1_humanoid_23dof.yml

    cspace: # joints which are actuated 
      joint_names:
        # - world  
        # - pelvis
        # - torso_link
        - left_shoulder_pitch_joint
        - left_shoulder_roll_joint
        - left_shoulder_yaw_joint
        - left_elbow_joint
        - left_wrist_roll_joint
        - dummy_ee_left_joint
      retract_config: [0, 0.3, 0.0, 0.5, 0.0, 0.0]
      
      # Initialize null_space_weight and cspace_distance_weight to a vector of length of joint_names and value 1. If you want to weigh the joints differently use values less than 1.
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_acceleration: 10.0 # todo: check this (a guess, I could not find the max jerk of G1 anywhere in the docs)
      max_jerk: 15.0 # todo: check this. (a guess, I could not find the max jerk of G1 anywhere in the docs)
