robot_cfg:
  kinematics:
    asset_root_path: robot/franka_3_arm
    base_link: base_link
    collision_link_names:
    - arm_0_panda_link0
    - arm_0_panda_link1
    - arm_0_panda_link2
    - arm_0_panda_link3
    - arm_0_panda_link4
    - arm_0_panda_link5
    - arm_0_panda_link6
    - arm_0_panda_link7
    - arm_0_panda_hand
    - arm_0_panda_leftfinger
    - arm_0_panda_rightfinger
    - arm_1_panda_link0
    - arm_1_panda_link1
    - arm_1_panda_link2
    - arm_1_panda_link3
    - arm_1_panda_link4
    - arm_1_panda_link5
    - arm_1_panda_link6
    - arm_1_panda_link7
    - arm_1_panda_hand
    - arm_1_panda_leftfinger
    - arm_1_panda_rightfinger
    - arm_2_panda_link0
    - arm_2_panda_link1
    - arm_2_panda_link2
    - arm_2_panda_link3
    - arm_2_panda_link4
    - arm_2_panda_link5
    - arm_2_panda_link6
    - arm_2_panda_link7
    - arm_2_panda_hand
    - arm_2_panda_leftfinger
    - arm_2_panda_rightfinger
    collision_spheres: "spheres/franka_3_arm_mesh.yml"
    collision_sphere_buffer: 0.004
    extra_collision_spheres: {"arm_0_attached_object": 4, "arm_1_attached_object": 4, "arm_2_attached_object": 4}
    use_global_cumul: True
    self_collision_ignore:
      {
        # Arm 0 self-collision ignores
        "arm_0_panda_link0": ["arm_0_panda_link1", "arm_0_panda_link2"],
        "arm_0_panda_link1": ["arm_0_panda_link2", "arm_0_panda_link3", "arm_0_panda_link4"],
        "arm_0_panda_link2": ["arm_0_panda_link3", "arm_0_panda_link4"],
        "arm_0_panda_link3": ["arm_0_panda_link4", "arm_0_panda_link6"],
        "arm_0_panda_link4":
          ["arm_0_panda_link5", "arm_0_panda_link6", "arm_0_panda_link7"],
        "arm_0_panda_link5": ["arm_0_panda_link6", "arm_0_panda_link7", "arm_0_panda_hand","arm_0_panda_leftfinger", "arm_0_panda_rightfinger"],
        "arm_0_panda_link6": ["arm_0_panda_link7", "arm_0_panda_hand", "arm_0_attached_object", "arm_0_panda_leftfinger", "arm_0_panda_rightfinger"],
        "arm_0_panda_link7": ["arm_0_panda_hand", "arm_0_attached_object", "arm_0_panda_leftfinger", "arm_0_panda_rightfinger"],
        "arm_0_panda_hand": ["arm_0_panda_leftfinger", "arm_0_panda_rightfinger","arm_0_attached_object"],
        "arm_0_panda_leftfinger": ["arm_0_panda_rightfinger", "arm_0_attached_object"],
        "arm_0_panda_rightfinger": ["arm_0_attached_object"],

        # Arm 1 self-collision ignores
        "arm_1_panda_link0": ["arm_1_panda_link1", "arm_1_panda_link2"],
        "arm_1_panda_link1": ["arm_1_panda_link2", "arm_1_panda_link3", "arm_1_panda_link4"],
        "arm_1_panda_link2": ["arm_1_panda_link3", "arm_1_panda_link4"],
        "arm_1_panda_link3": ["arm_1_panda_link4", "arm_1_panda_link6"],
        "arm_1_panda_link4":
          ["arm_1_panda_link5", "arm_1_panda_link6", "arm_1_panda_link7"],
        "arm_1_panda_link5": ["arm_1_panda_link6", "arm_1_panda_link7", "arm_1_panda_hand","arm_1_panda_leftfinger", "arm_1_panda_rightfinger"],
        "arm_1_panda_link6": ["arm_1_panda_link7", "arm_1_panda_hand", "arm_1_attached_object", "arm_1_panda_leftfinger", "arm_1_panda_rightfinger"],
        "arm_1_panda_link7": ["arm_1_panda_hand", "arm_1_attached_object", "arm_1_panda_leftfinger", "arm_1_panda_rightfinger"],
        "arm_1_panda_hand": ["arm_1_panda_leftfinger", "arm_1_panda_rightfinger","arm_1_attached_object"],
        "arm_1_panda_leftfinger": ["arm_1_panda_rightfinger", "arm_1_attached_object"],
        "arm_1_panda_rightfinger": ["arm_1_attached_object"],

        # Arm 2 self-collision ignores
        "arm_2_panda_link0": ["arm_2_panda_link1", "arm_2_panda_link2"],
        "arm_2_panda_link1": ["arm_2_panda_link2", "arm_2_panda_link3", "arm_2_panda_link4"],
        "arm_2_panda_link2": ["arm_2_panda_link3", "arm_2_panda_link4"],
        "arm_2_panda_link3": ["arm_2_panda_link4", "arm_2_panda_link6"],
        "arm_2_panda_link4":
          ["arm_2_panda_link5", "arm_2_panda_link6", "arm_2_panda_link7"],
        "arm_2_panda_link5": ["arm_2_panda_link6", "arm_2_panda_link7", "arm_2_panda_hand","arm_2_panda_leftfinger", "arm_2_panda_rightfinger"],
        "arm_2_panda_link6": ["arm_2_panda_link7", "arm_2_panda_hand", "arm_2_attached_object", "arm_2_panda_leftfinger", "arm_2_panda_rightfinger"],
        "arm_2_panda_link7": ["arm_2_panda_hand", "arm_2_attached_object", "arm_2_panda_leftfinger", "arm_2_panda_rightfinger"],
        "arm_2_panda_hand": ["arm_2_panda_leftfinger", "arm_2_panda_rightfinger","arm_2_attached_object"],
        "arm_2_panda_leftfinger": ["arm_2_panda_rightfinger", "arm_2_attached_object"],
        "arm_2_panda_rightfinger": ["arm_2_attached_object"],
      }

    self_collision_buffer:
      {
        # Arm 0 collision buffers
        "arm_0_panda_link0": 0.1,
        "arm_0_panda_link1": 0.05,
        "arm_0_panda_link2": 0.0,
        "arm_0_panda_link3": 0.0,
        "arm_0_panda_link4": 0.0,
        "arm_0_panda_link5": 0.0,
        "arm_0_panda_link6": 0.0,
        "arm_0_panda_link7": 0.0,
        "arm_0_panda_hand": 0.02,
        "arm_0_panda_leftfinger": 0.01,
        "arm_0_panda_rightfinger": 0.01,
        "arm_0_attached_object": 0.0,
        # Arm 1 collision buffers
        "arm_1_panda_link0": 0.1,
        "arm_1_panda_link1": 0.05,
        "arm_1_panda_link2": 0.0,
        "arm_1_panda_link3": 0.0,
        "arm_1_panda_link4": 0.0,
        "arm_1_panda_link5": 0.0,
        "arm_1_panda_link6": 0.0,
        "arm_1_panda_link7": 0.0,
        "arm_1_panda_hand": 0.02,
        "arm_1_panda_leftfinger": 0.01,
        "arm_1_panda_rightfinger": 0.01,
        "arm_1_attached_object": 0.0,
        # Arm 2 collision buffers
        "arm_2_panda_link0": 0.1,
        "arm_2_panda_link1": 0.05,
        "arm_2_panda_link2": 0.0,
        "arm_2_panda_link3": 0.0,
        "arm_2_panda_link4": 0.0,
        "arm_2_panda_link5": 0.0,
        "arm_2_panda_link6": 0.0,
        "arm_2_panda_link7": 0.0,
        "arm_2_panda_hand": 0.02,
        "arm_2_panda_leftfinger": 0.01,
        "arm_2_panda_rightfinger": 0.01,
        "arm_2_attached_object": 0.0,
      }
    cspace:
      cspace_distance_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      joint_names:
      - arm_0_panda_joint1
      - arm_0_panda_joint2
      - arm_0_panda_joint3
      - arm_0_panda_joint4
      - arm_0_panda_joint5
      - arm_0_panda_joint6
      - arm_0_panda_joint7
      - arm_0_panda_finger_joint1
      - arm_0_panda_finger_joint2
      - arm_1_panda_joint1
      - arm_1_panda_joint2
      - arm_1_panda_joint3
      - arm_1_panda_joint4
      - arm_1_panda_joint5
      - arm_1_panda_joint6
      - arm_1_panda_joint7
      - arm_1_panda_finger_joint1
      - arm_1_panda_finger_joint2
      - arm_2_panda_joint1
      - arm_2_panda_joint2
      - arm_2_panda_joint3
      - arm_2_panda_joint4
      - arm_2_panda_joint5
      - arm_2_panda_joint6
      - arm_2_panda_joint7
      - arm_2_panda_finger_joint1
      - arm_2_panda_finger_joint2
      max_acceleration: 15.0
      max_jerk: 500.0
      null_space_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      retract_config:
      - 0.0
      - -1.3
      - 0.0
      - -2.5
      - 0.0
      - 1.0
      - 0.0
      - 0.04
      - 0.04
      - 0.0
      - -1.3
      - 0.0
      - -2.5
      - 0.0
      - 1.0
      - 0.0
      - 0.04
      - 0.04
      - 0.0
      - -1.3
      - 0.0
      - -2.5
      - 0.0
      - 1.0
      - 0.0
      - 0.04
      - 0.04
    ee_link: arm_0_panda_hand
    link_names:
    - arm_0_panda_hand
    - arm_1_panda_hand
    - arm_2_panda_hand
    lock_joints: {
      "arm_0_panda_finger_joint1": 0.04, 
      "arm_0_panda_finger_joint2": 0.04,
      "arm_1_panda_finger_joint1": 0.04, 
      "arm_1_panda_finger_joint2": 0.04,
      "arm_2_panda_finger_joint1": 0.04, 
      "arm_2_panda_finger_joint2": 0.04
    }
    urdf_path: robot/franka_3_arm/franka_3_arm.urdf
    use_global_cumul: true
    use_usd_kinematics: false
