##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    use_usd_kinematics: False
    isaac_usd_path: "/Isaac/Robots/Franka/franka.usd"
    usd_path: "robot/non_shipping/franka/franka_panda_meters.usda"
    usd_robot_root: "/panda"
    usd_flip_joints: {
    "left_panda_joint1": "Z",
    "left_panda_joint2": "Z",
    "left_panda_joint3": "Z",
    "left_panda_joint4": "Z",
    "left_panda_joint5": "Z",
    "left_panda_joint6": "Z",
    "left_panda_joint7": "Z",
    "left_panda_finger_joint1": "Y",
    "left_panda_finger_joint2": "Y",
    "right_panda_joint1": "Z",
    "right_panda_joint2": "Z",
    "right_panda_joint3": "Z",
    "right_panda_joint4": "Z",
    "right_panda_joint5": "Z",
    "right_panda_joint6": "Z",
    "right_panda_joint7": "Z",
    "right_panda_finger_joint1": "Y",
    "right_panda_finger_joint2": "Y",
    }

    usd_flip_joint_limits: ["left_panda_finger_joint2", "right_panda_finger_joint2"]
    urdf_path: "robot/franka_dual_arm/franka_dual_arm.urdf"
    asset_root_path: "robot/franka_dual_arm"
    base_link: "base_link"
    ee_link: "left_panda_hand"  # Primary end effector
    collision_link_names:
      [
        # Left arm links
        "left_panda_link0",
        "left_panda_link1",
        "left_panda_link2",
        "left_panda_link3",
        "left_panda_link4",
        "left_panda_link5",
        "left_panda_link6",
        "left_panda_link7",
        "left_panda_hand",
        "left_panda_leftfinger",
        "left_panda_rightfinger",
        # Right arm links
        "right_panda_link0",
        "right_panda_link1",
        "right_panda_link2",
        "right_panda_link3",
        "right_panda_link4",
        "right_panda_link5",
        "right_panda_link6",
        "right_panda_link7",
        "right_panda_hand",
        "right_panda_leftfinger",
        "right_panda_rightfinger",
        # Attached objects
        "left_attached_object",
        "right_attached_object",
      ]
    collision_spheres: "spheres/franka_dual_arm_mesh.yml"
    collision_sphere_buffer: 0.004 # 0.0025
    extra_collision_spheres: {"left_attached_object": 4, "right_attached_object": 4}
    use_global_cumul: True
    self_collision_ignore:
      {
        # Left arm self-collision ignores
        "left_panda_link0": ["left_panda_link1", "left_panda_link2"],
        "left_panda_link1": ["left_panda_link2", "left_panda_link3", "left_panda_link4"],
        "left_panda_link2": ["left_panda_link3", "left_panda_link4"],
        "left_panda_link3": ["left_panda_link4", "left_panda_link6"],
        "left_panda_link4":
          ["left_panda_link5", "left_panda_link6", "left_panda_link7", "left_panda_link8"],
        "left_panda_link5": ["left_panda_link6", "left_panda_link7", "left_panda_hand","left_panda_leftfinger", "left_panda_rightfinger"],
        "left_panda_link6": ["left_panda_link7", "left_panda_hand", "left_attached_object", "left_panda_leftfinger", "left_panda_rightfinger"],
        "left_panda_link7": ["left_panda_hand", "left_attached_object", "left_panda_leftfinger", "left_panda_rightfinger"],
        "left_panda_hand": ["left_panda_leftfinger", "left_panda_rightfinger","left_attached_object"],
        "left_panda_leftfinger": ["left_panda_rightfinger", "left_attached_object"],
        "left_panda_rightfinger": ["left_attached_object"],

        # Right arm self-collision ignores
        "right_panda_link0": ["right_panda_link1", "right_panda_link2"],
        "right_panda_link1": ["right_panda_link2", "right_panda_link3", "right_panda_link4"],
        "right_panda_link2": ["right_panda_link3", "right_panda_link4"],
        "right_panda_link3": ["right_panda_link4", "right_panda_link6"],
        "right_panda_link4":
          ["right_panda_link5", "right_panda_link6", "right_panda_link7", "right_panda_link8"],
        "right_panda_link5": ["right_panda_link6", "right_panda_link7", "right_panda_hand","right_panda_leftfinger", "right_panda_rightfinger"],
        "right_panda_link6": ["right_panda_link7", "right_panda_hand", "right_attached_object", "right_panda_leftfinger", "right_panda_rightfinger"],
        "right_panda_link7": ["right_panda_hand", "right_attached_object", "right_panda_leftfinger", "right_panda_rightfinger"],
        "right_panda_hand": ["right_panda_leftfinger", "right_panda_rightfinger","right_attached_object"],
        "right_panda_leftfinger": ["right_panda_rightfinger", "right_attached_object"],
        "right_panda_rightfinger": ["right_attached_object"],
      }

    self_collision_buffer:
      {
        # Left arm collision buffers
        "left_panda_link0": 0.1,
        "left_panda_link1": 0.05,
        "left_panda_link2": 0.0,
        "left_panda_link3": 0.0,
        "left_panda_link4": 0.0,
        "left_panda_link5": 0.0,
        "left_panda_link6": 0.0,
        "left_panda_link7": 0.0,
        "left_panda_hand": 0.02,
        "left_panda_leftfinger": 0.01,
        "left_panda_rightfinger": 0.01,
        "left_attached_object": 0.0,
        # Right arm collision buffers
        "right_panda_link0": 0.1,
        "right_panda_link1": 0.05,
        "right_panda_link2": 0.0,
        "right_panda_link3": 0.0,
        "right_panda_link4": 0.0,
        "right_panda_link5": 0.0,
        "right_panda_link6": 0.0,
        "right_panda_link7": 0.0,
        "right_panda_hand": 0.02,
        "right_panda_leftfinger": 0.01,
        "right_panda_rightfinger": 0.01,
        "right_attached_object": 0.0,
      }
    mesh_link_names:
      [
        # Left arm mesh links
        "left_panda_link0",
        "left_panda_link1",
        "left_panda_link2",
        "left_panda_link3",
        "left_panda_link4",
        "left_panda_link5",
        "left_panda_link6",
        "left_panda_link7",
        "left_panda_hand",
        "left_panda_leftfinger",
        "left_panda_rightfinger",
        # Right arm mesh links
        "right_panda_link0",
        "right_panda_link1",
        "right_panda_link2",
        "right_panda_link3",
        "right_panda_link4",
        "right_panda_link5",
        "right_panda_link6",
        "right_panda_link7",
        "right_panda_hand",
        "right_panda_leftfinger",
        "right_panda_rightfinger",
      ]
    lock_joints: {
      "left_panda_finger_joint1": 0.04, 
      "left_panda_finger_joint2": 0.04,
      "right_panda_finger_joint1": 0.04, 
      "right_panda_finger_joint2": 0.04
    }
    extra_links: {
      "left_attached_object": {
        "parent_link_name": "left_panda_hand",
        "link_name": "left_attached_object", 
        "fixed_transform": [0,0,0,1,0,0,0], 
        "joint_type":"FIXED",
        "joint_name": "left_attach_joint" 
      },
      "right_attached_object": {
        "parent_link_name": "right_panda_hand",
        "link_name": "right_attached_object", 
        "fixed_transform": [0,0,0,1,0,0,0], 
        "joint_type":"FIXED",
        "joint_name": "right_attach_joint" 
      }
    }
    cspace:
      joint_names: [
        # Left arm joints
        "left_panda_joint1","left_panda_joint2","left_panda_joint3","left_panda_joint4", 
        "left_panda_joint5", "left_panda_joint6","left_panda_joint7",
        "left_panda_finger_joint1", "left_panda_finger_joint2",
        # Right arm joints  
        "right_panda_joint1","right_panda_joint2","right_panda_joint3","right_panda_joint4", 
        "right_panda_joint5", "right_panda_joint6","right_panda_joint7",
        "right_panda_finger_joint1", "right_panda_finger_joint2"
      ]
      # Retract configuration for both arms (18 total joints: 9 per arm)
      retract_config: [
        # Left arm retract: [0.0, -1.3, 0.0, -2.5, 0.0, 1.0, 0., 0.04, 0.04]
        0.0, -1.3, 0.0, -2.5, 0.0, 1.0, 0., 0.04, 0.04,
        # Right arm retract: [0.0, -1.3, 0.0, -2.5, 0.0, 1.0, 0., 0.04, 0.04]  
        0.0, -1.3, 0.0, -2.5, 0.0, 1.0, 0., 0.04, 0.04
      ]
      null_space_weight: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
      cspace_distance_weight: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
      max_acceleration: 15.0
      max_jerk: 500.0 