##
## Simple disk robot configuration for CuRobo
##

robot_cfg:
  kinematics:
    use_usd_kinematics: False
    urdf_path: "robot/simple_disk_description/simple_disk_tiny.urdf"
    asset_root_path: "robot/simple_disk_description"
    base_link: "world"
    ee_link: "ee_link"
    collision_link_names: ["base_link", "ee_link"]
    collision_spheres: spheres/simple_disk_tiny.yml
    collision_sphere_buffer: 0.001
    use_global_cumul: True
    self_collision_ignore:
      {
        "base_link": ["ee_link"],
        "ee_link": ["base_link"],
      }
    self_collision_buffer:
      {
        "base_link": 0.0,
        "ee_link": 0.0,
      }
    mesh_link_names:
      [
        "base_link",
        "ee_link",
      ]
    lock_joints: {}
    cspace:
      joint_names: ["joint_x", "joint_y"]
      retract_config: [0.0, 0.0]
      null_space_weight: [1, 1]
      cspace_distance_weight: [1, 1]
      max_acceleration: 2.0 # 1.0 # 15.0 # 0.5 # 0.3 # 1.0 # 5.0
      max_jerk: 50.0 # 20.0 # 1.0 # 50.0 