##
## Simple disk robot configuration for CuRobo
##

robot_cfg:
  kinematics:
    use_usd_kinematics: False
    urdf_path: "robot/simple_disk_description/simple_disk.urdf"
    asset_root_path: "robot/simple_disk_description"
    base_link: "base_link"
    ee_link: "disk_base"
    collision_link_names: null
    collision_spheres: spheres/simple_disk.yml
    collision_sphere_buffer: 0.02
    use_global_cumul: True
    self_collision_ignore: null
    self_collision_buffer: null
    mesh_link_names:
      [
        "disk_base",
      ]
    lock_joints: {}
    cspace:
      joint_names: ["base_x", "base_y", "base_theta"]
      retract_config: [0.0, 0.0, 0.0]
      null_space_weight: [1, 1, 1]
      cspace_distance_weight: [1, 1, 1]
      max_acceleration: 5.0
      max_jerk: 50.0 