# Default initial positions for franka_dual_arm's ros2_control fake system
# Matching the home positions defined in SRDF for more natural arm poses

initial_positions:
  left_panda_joint1: 0
  left_panda_joint2: 0
  left_panda_joint3: 0
  left_panda_joint4: -1.5708
  left_panda_joint5: 0
  left_panda_joint6: 0
  left_panda_joint7: 0
  right_panda_joint1: 0
  right_panda_joint2: 0
  right_panda_joint3: 0
  right_panda_joint4: -1.5708
  right_panda_joint5: 0
  right_panda_joint6: 0
  right_panda_joint7: 0