# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Individual arm controllers (auto-started for MoveIt compatibility)
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Combined controller (defined but not auto-started to avoid conflicts)
    all_arms_controller:
      type: joint_trajectory_controller/JointTrajectoryController


# Individual arm controllers for single-arm planning (MoveIt tutorial approach)
left_arm_controller:
  ros__parameters:
    joints:
      - left_panda_joint1
      - left_panda_joint2
      - left_panda_joint3
      - left_panda_joint4
      - left_panda_joint5
      - left_panda_joint6
      - left_panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_arm_controller:
  ros__parameters:
    joints:
      - right_panda_joint1
      - right_panda_joint2
      - right_panda_joint3
      - right_panda_joint4
      - right_panda_joint5
      - right_panda_joint6
      - right_panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# Combined controller for dual-arm centralized planning (not auto-started)
all_arms_controller:
  ros__parameters:
    joints:
      - left_panda_joint1
      - left_panda_joint2
      - left_panda_joint3
      - left_panda_joint4
      - left_panda_joint5
      - left_panda_joint6
      - left_panda_joint7
      - right_panda_joint1
      - right_panda_joint2
      - right_panda_joint3
      - right_panda_joint4
      - right_panda_joint5
      - right_panda_joint6
      - right_panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity