
robot_cfg:
  kinematics:
    base_link: base_link
    ee_link: dummy_ee_right_link
    use_usd_kinematics: False

    # File paths
    urdf_path: "robot/g1_feb26/unitreerobotics unitree_ros master robots-g1_description/g1_right_arm_only.urdf"

    # Collision configuration
    collision_link_names:
      - right_shoulder_pitch_link
      - right_shoulder_roll_link
      - right_shoulder_yaw_link
      - right_elbow_link
      - right_wrist_roll_link
      - right_wrist_pitch_link
      - right_wrist_yaw_link
      - right_rubber_hand
      
    mesh_link_names:
      - base_link
      - right_shoulder_pitch_link
      - right_shoulder_roll_link
      - right_shoulder_yaw_link
      - right_elbow_link
      - right_wrist_roll_link
      - right_wrist_pitch_link
      - right_wrist_yaw_link
      - right_rubber_hand
      - dummy_ee_right_link
      
    lock_joints: {right_wrist_yaw_joint: 0.0,right_wrist_pitch_joint: 0.0}
    
    collision_sphere_buffer: 0.0001

    self_collision_buffer:
      right_shoulder_pitch_link: 0.0001
      right_shoulder_roll_link: 0.0001
      right_shoulder_yaw_link: 0.0001
      right_elbow_link: 0.0001
      right_rubber_hand: 0.0001

    self_collision_ignore: {
      "right_shoulder_pitch_link": ["right_shoulder_roll_link", "right_shoulder_yaw_link", "right_elbow_link"],
      "right_shoulder_roll_link": ["right_shoulder_pitch_link", "right_shoulder_yaw_link", "right_elbow_link"],
      "right_shoulder_yaw_link": ["right_shoulder_roll_link", "right_shoulder_pitch_link", "right_elbow_link"],
      "right_elbow_link": ["right_shoulder_roll_link", "right_shoulder_pitch_link", "right_shoulder_yaw_link", "right_rubber_hand", "right_wrist_roll_link", "right_wrist_pitch_link", "right_wrist_yaw_link"],
      "right_wrist_roll_link": ["right_elbow_link", "right_wrist_pitch_link", "right_wrist_yaw_link", "right_rubber_hand"],
      "right_wrist_pitch_link": ["right_wrist_roll_link", "right_wrist_yaw_link", "right_rubber_hand", "right_elbow_link"],
      "right_wrist_yaw_link": ["right_wrist_roll_link", "right_wrist_pitch_link", "right_rubber_hand", "right_elbow_link"],
      "right_rubber_hand": ["right_elbow_link", "right_wrist_roll_link", "right_wrist_pitch_link", "right_wrist_yaw_link"],
    }

    collision_spheres: spheres/g1_right_arm_only.yml

    cspace:
      joint_names:
        - right_shoulder_pitch_joint
        - right_shoulder_roll_joint
        - right_shoulder_yaw_joint
        - right_elbow_joint
        - right_wrist_roll_joint
        - right_wrist_pitch_joint
        - right_wrist_yaw_joint
      retract_config: [0, -0.3, 0.0, 0.5, 0.0, 0.0,0.0]
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_acceleration: 20.0
      max_jerk: 30.0
