# Robot Configuration Template
# This file defines how robots are configured for MoveIt2 planning with Isaac Sim

# Default robot configuration (Panda arm)
default_robot:
  name: "panda"
  urdf_path: /workspace/rl_for_curobo/projects_root/ros/workspaces/isaac_moveit/src/moveit2_isaac_sim_integration/config/example_urdf_for_testing/franka_description/panda.urdf
  
  # Isaac Sim specific settings
  isaac_sim:
    stage_path: "/Franka"
    usd_path: # "/Isaac/Robots/Franka/franka_alt_fingers.usd" 
    position: [0.0, -0.64, 0.0]  # [x, y, z]
    orientation: [0.0, 0.0, 1.0, 90.0]  # [x, y, z, angle_degrees]
    
  # MoveIt2 configuration
  moveit2:
    # Main planning group (usually the whole robot)
    planning_group: "panda_arm"
    
    # End effectors and their target configurations
    end_effectors:
      - name: "panda_hand"
        planning_group: "panda_arm"
        link_name: "panda_link8"
        reference_frame: "panda_link0"
        default_target_pose:
          position: [0.5, 0.0, 0.5]  # [x, y, z]
          orientation: [0.0, 0.0, 0.0, 1.0]  # [x, y, z, w] quaternion
          
    # Joint names for the robot
    joint_names:
      - "panda_joint1"
      - "panda_joint2"
      - "panda_joint3"
      - "panda_joint4"
      - "panda_joint5"
      - "panda_joint6"
      - "panda_joint7"
      
    # Joint limits (optional, will be read from URDF if not specified)
    joint_limits:
      panda_joint1: [-2.8973, 2.8973]
      panda_joint2: [-1.7628, 1.7628]
      panda_joint3: [-2.8973, 2.8973]
      panda_joint4: [-3.0718, -0.0698]
      panda_joint5: [-2.8973, 2.8973]
      panda_joint6: [-0.0175, 3.7525]
      panda_joint7: [-2.8973, 2.8973]
      
    # Home position
    home_position:
      - 0.0
      - -0.785
      - 0.0
      - -2.356
      - 0.0
      - 1.571
      - 0.785
      
  # ROS2 topic configuration
  ros2_topics:
    isaac_joint_commands: "/isaac_joint_commands"
    isaac_joint_states: "/isaac_joint_states"
    moveit_joint_trajectory: "/panda_arm_controller/joint_trajectory"
    
  # Planning configuration
  planning:
    default_planner: "RRTConnect"
    planning_time: 5.0
    max_velocity_scaling_factor: 0.1
    max_acceleration_scaling_factor: 0.1
    
  # Simulation settings
  simulation:
    step_size: 0.01  # seconds
    target_change_interval: 100  # steps
    target_pose_tolerance: 0.01  # meters
    target_visualization_size: 0.1  # meters (cuboid size)
    
# Example multi-arm robot configuration
dual_arm_robot:
  name: "dual_panda"
  urdf_path: "/path/to/dual_panda.urdf"
  
  isaac_sim:
    stage_path: "/DualPanda"
    usd_path: "/path/to/dual_panda.usd"
    position: [0.0, 0.0, 0.0]
    orientation: [0.0, 0.0, 0.0, 0.0]
    
  moveit2:
    planning_group: "dual_panda_arms"
    
    end_effectors:
      - name: "left_panda_hand"
        planning_group: "left_panda_arm"
        link_name: "left_panda_link8"
        reference_frame: "base_link"
        default_target_pose:
          position: [0.5, 0.5, 0.5]
          orientation: [0.0, 0.0, 0.0, 1.0]
          
      - name: "right_panda_hand"
        planning_group: "right_panda_arm"
        link_name: "right_panda_link8"
        reference_frame: "base_link"
        default_target_pose:
          position: [0.5, -0.5, 0.5]
          orientation: [0.0, 0.0, 0.0, 1.0]
          
    joint_names:
      - "left_panda_joint1"
      - "left_panda_joint2"
      - "left_panda_joint3"
      - "left_panda_joint4"
      - "left_panda_joint5"
      - "left_panda_joint6"
      - "left_panda_joint7"
      - "right_panda_joint1"
      - "right_panda_joint2"
      - "right_panda_joint3"
      - "right_panda_joint4"
      - "right_panda_joint5"
      - "right_panda_joint6"
      - "right_panda_joint7"
      
    home_position:
      - 0.0, -0.785, 0.0, -2.356, 0.0, 1.571, 0.785  # left arm
      - 0.0, -0.785, 0.0, -2.356, 0.0, 1.571, 0.785  # right arm
      
  ros2_topics:
    isaac_joint_commands: "/isaac_joint_commands"
    isaac_joint_states: "/isaac_joint_states"
    moveit_joint_trajectory: "/dual_panda_controller/joint_trajectory"
    
  planning:
    default_planner: "RRTConnect"
    planning_time: 10.0  # More time for dual arm planning
    max_velocity_scaling_factor: 0.05
    max_acceleration_scaling_factor: 0.05
    
  simulation:
    step_size: 0.01
    target_change_interval: 100
    target_pose_tolerance: 0.01
    target_visualization_size: 0.1 