joint_limits:
  panda_joint1:
    has_acceleration_limits: false
    has_position_limits: true
    has_velocity_limits: true
    max_position: 2.8973
    max_velocity: 2.175
    min_position: -2.8973
  panda_joint2:
    has_acceleration_limits: false
    has_position_limits: true
    has_velocity_limits: true
    max_position: 1.7628
    max_velocity: 2.175
    min_position: -1.7628
  panda_joint3:
    has_acceleration_limits: false
    has_position_limits: true
    has_velocity_limits: true
    max_position: 2.8973
    max_velocity: 2.175
    min_position: -2.8973
  panda_joint4:
    has_acceleration_limits: false
    has_position_limits: true
    has_velocity_limits: true
    max_position: -0.0698
    max_velocity: 2.175
    min_position: -3.0718
  panda_joint5:
    has_acceleration_limits: false
    has_position_limits: true
    has_velocity_limits: true
    max_position: 2.8975
    max_velocity: 2.61
    min_position: -2.8975
  panda_joint6:
    has_acceleration_limits: false
    has_position_limits: true
    has_velocity_limits: true
    max_position: 3.7525
    max_velocity: 2.61
    min_position: -0.0175
  panda_joint7:
    has_acceleration_limits: false
    has_position_limits: true
    has_velocity_limits: true
    max_position: 2.8973
    max_velocity: 2.61
    min_position: -2.8973
