# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - all_arms_controller
    - left_arm_controller
    - right_arm_controller
    

  # Individual arm controllers (default for MoveIt tutorial compatibility)
  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - left_panda_joint1
      - left_panda_joint2
      - left_panda_joint3
      - left_panda_joint4
      - left_panda_joint5
      - left_panda_joint6
      - left_panda_joint7
    action_ns: follow_joint_trajectory
    # default: true
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - right_panda_joint1
      - right_panda_joint2
      - right_panda_joint3
      - right_panda_joint4
      - right_panda_joint5
      - right_panda_joint6
      - right_panda_joint7
    action_ns: follow_joint_trajectory
    default: true
  # Combined controller for dual-arm centralized planning (available but not default)
  all_arms_controller:
    type: FollowJointTrajectory
    joints:
      - left_panda_joint1
      - left_panda_joint2
      - left_panda_joint3
      - left_panda_joint4
      - left_panda_joint5
      - left_panda_joint6
      - left_panda_joint7
      - right_panda_joint1
      - right_panda_joint2
      - right_panda_joint3
      - right_panda_joint4
      - right_panda_joint5
      - right_panda_joint6
      - right_panda_joint7
    action_ns: follow_joint_trajectory
    default: false